from enum import StrEnum


class Environment(StrEnum):
    DEMO = "demo"
    LIVE = "live"


class DividendCashAction(StrEnum):
    REINVEST = "REINVEST"
    TO_ACCOUNT_CASH = "TO_ACCOUNT_CASH"


class PieStatus(StrEnum):
    AHEAD = "AHEAD"
    ON_TRACK = "ON_TRACK"
    BEHIND = "BEHIND"


class InstrumentType(StrEnum):
    CRYPTOCURRENCY = "CRYPTOCURRENCY"
    ETF = "ETF"
    FOREX = "FOREX"
    FUTURES = "FUTURES"
    INDEX = "INDEX"
    STOCK = "STOCK"
    WARRANT = "WARRANT"
    CRYPTO = "CRYPTO"
    CVR = "CVR"
    CORPACT = "CORPACT"


class TimeEventType(StrEnum):
    OPEN = "OPEN"
    CLOSE = "CLOSE"
    BREAK_START = "BREAK_START"
    BREAK_END = "BREAK_END"
    PRE_MARKET_OPEN = "PRE_MARKET_OPEN"
    AFTER_HOURS_OPEN = "AFTER_HOURS_OPEN"
    AFTER_HOURS_CLOSE = "AFTER_HOURS_CLOSE"
    OVERNIGHT_OPEN = "OVERNIGHT_OPEN"


class TimeValidity(StrEnum):
    DAY = "DAY"
    GOOD_TILL_CANCEL = "GOOD_TILL_CANCEL"


class OrderType(StrEnum):
    LIMIT = "LIMIT"
    STOP = "STOP"
    MARKET = "MARKET"
    STOP_LIMIT = "STOP_LIMIT"


class OrderSide(StrEnum):
    BUY = "BUY"
    SELL = "SELL"


class OrderStatus(StrEnum):
    LOCAL = "LOCAL"
    UNCONFIRMED = "UNCONFIRMED"
    CONFIRMED = "CONFIRMED"
    NEW = "NEW"
    CANCELLING = "CANCELLING"
    CANCELLED = "CANCELLED"
    PARTIALLY_FILLED = "PARTIALLY_FILLED"
    FILLED = "FILLED"
    REJECTED = "REJECTED"
    REPLACING = "REPLACING"
    REPLACED = "REPLACED"


class OrderStrategy(StrEnum):
    QUANTITY = "QUANTITY"
    VALUE = "VALUE"


class OrderInitiatedFrom(StrEnum):
    API = "API"
    IOS = "IOS"
    ANDROID = "ANDROID"
    WEB = "WEB"
    SYSTEM = "SYSTEM"
    AUTOINVEST = "AUTOINVEST"


class FillTradingMethod(StrEnum):
    TOTV = "TOTV"
    OTC = "OTC"


class FillType(StrEnum):
    TRADE = "TRADE"
    STOCK_SPLIT = "STOCK_SPLIT"
    STOCK_DISTRIBUTION = "STOCK_DISTRIBUTION"
    FOP = "FOP"
    FOP_CORRECTION = "FOP_CORRECTION"
    CUSTOM_STOCK_DISTRIBUTION = "CUSTOM_STOCK_DISTRIBUTION"
    EQUITY_RIGHTS = "EQUITY_RIGHTS"
    SCRIP_STOCK_DIVIDENDS = "SCRIP_STOCK_DIVIDENDS"
    STOCK_DIVIDENDS = "STOCK_DIVIDENDS"
    STOCK_ACQUISITION = "STOCK_ACQUISITION"
    CASH_AND_STOCK_ACQUISITION = "CASH_AND_STOCK_ACQUISITION"
    SPIN_OFF = "SPIN_OFF"


class TaxName(StrEnum):
    COMMISSION_TURNOVER = "COMMISSION_TURNOVER"
    CURRENCY_CONVERSION_FEE = "CURRENCY_CONVERSION_FEE"
    FINRA_FEE = "FINRA_FEE"
    FRENCH_TRANSACTION_TAX = "FRENCH_TRANSACTION_TAX"
    PTM_LEVY = "PTM_LEVY"
    STAMP_DUTY = "STAMP_DUTY"
    STAMP_DUTY_RESERVE_TAX = "STAMP_DUTY_RESERVE_TAX"
    TRANSACTION_FEE = "TRANSACTION_FEE"


class DividendType(StrEnum):
    ORDINARY = "ORDINARY"
    BONUS = "BONUS"
    PROPERTY_INCOME = "PROPERTY_INCOME"
    RETURN_OF_CAPITAL_NON_US = "RETURN_OF_CAPITAL_NON_US"
    DEMERGER = "DEMERGER"
    INTEREST = "INTEREST"
    CAPITAL_GAINS_DISTRIBUTION_NON_US = "CAPITAL_GAINS_DISTRIBUTION_NON_US"
    INTERIM_LIQUIDATION = "INTERIM_LIQUIDATION"
    ORDINARY_MANUFACTURED_PAYMENT = "ORDINARY_MANUFACTURED_PAYMENT"
    BONUS_MANUFACTURED_PAYMENT = "BONUS_MANUFACTURED_PAYMENT"
    PROPERTY_INCOME_MANUFACTURED_PAYMENT = "PROPERTY_INCOME_MANUFACTURED_PAYMENT"
    RETURN_OF_CAPITAL_NON_US_MANUFACTURED_PAYMENT = "RETURN_OF_CAPITAL_NON_US_MANUFACTURED_PAYMENT"
    DEMERGER_MANUFACTURED_PAYMENT = "DEMERGER_MANUFACTURED_PAYMENT"
    INTEREST_MANUFACTURED_PAYMENT = "INTEREST_MANUFACTURED_PAYMENT"
    CAPITAL_GAINS_DISTRIBUTION_NON_US_MANUFACTURED_PAYMENT = (
        "CAPITAL_GAINS_DISTRIBUTION_NON_US_MANUFACTURED_PAYMENT"
    )
    INTERIM_LIQUIDATION_MANUFACTURED_PAYMENT = "INTERIM_LIQUIDATION_MANUFACTURED_PAYMENT"
    INTEREST_PAID_BY_US_OBLIGORS = "INTEREST_PAID_BY_US_OBLIGORS"
    INTEREST_PAID_BY_FOREIGN_CORPORATIONS = "INTEREST_PAID_BY_FOREIGN_CORPORATIONS"
    DIVIDENDS_PAID_BY_US_CORPORATIONS = "DIVIDENDS_PAID_BY_US_CORPORATIONS"
    DIVIDENDS_PAID_BY_FOREIGN_CORPORATIONS = "DIVIDENDS_PAID_BY_FOREIGN_CORPORATIONS"
    CAPITAL_GAINS = "CAPITAL_GAINS"
    REAL_PROPERTY_INCOME_AND_NATURAL_RESOURCES_ROYALTIES = (
        "REAL_PROPERTY_INCOME_AND_NATURAL_RESOURCES_ROYALTIES"
    )
    OTHER_INCOME = "OTHER_INCOME"
    QUALIFIED_INVESTMENT_ENTITY = "QUALIFIED_INVESTMENT_ENTITY"
    TRUST_DISTRIBUTION = "TRUST_DISTRIBUTION"
    PUBLICLY_TRADED_PARTNERSHIP_DISTRIBUTION = "PUBLICLY_TRADED_PARTNERSHIP_DISTRIBUTION"
    CAPITAL_GAINS_DISTRIBUTION = "CAPITAL_GAINS_DISTRIBUTION"
    RETURN_OF_CAPITAL = "RETURN_OF_CAPITAL"
    OTHER_DIVIDEND_EQUIVALENT = "OTHER_DIVIDEND_EQUIVALENT"
    TAX_EVENT_1446F_FOR_PUBLICLY_TRADED_SECURITIES = (
        "TAX_EVENT_1446F_FOR_PUBLICLY_TRADED_SECURITIES"
    )
    PTP_UNCHARACTERISED_INCOME = "PTP_UNCHARACTERISED_INCOME"
    MULTIPLE_1042S_TAX_COMPONENTS = "MULTIPLE_1042S_TAX_COMPONENTS"
    DIVIDEND = "DIVIDEND"
    SHORT_TERM_CAPITAL_GAINS = "SHORT_TERM_CAPITAL_GAINS"
    LONG_TERM_CAPITAL_GAINS = "LONG_TERM_CAPITAL_GAINS"
    PROPERTY_INCOME_DISTRIBUTION = "PROPERTY_INCOME_DISTRIBUTION"
    TAX_EXEMPTED = "TAX_EXEMPTED"
    INTEREST_PAID_BY_US_OBLIGORS_MANUFACTURED_PAYMENT = (
        "INTEREST_PAID_BY_US_OBLIGORS_MANUFACTURED_PAYMENT"
    )
    INTEREST_PAID_BY_FOREIGN_CORPORATIONS_MANUFACTURED_PAYMENT = (
        "INTEREST_PAID_BY_FOREIGN_CORPORATIONS_MANUFACTURED_PAYMENT"
    )
    DIVIDENDS_PAID_BY_US_CORPORATIONS_MANUFACTURED_PAYMENT = (
        "DIVIDENDS_PAID_BY_US_CORPORATIONS_MANUFACTURED_PAYMENT"
    )
    DIVIDENDS_PAID_BY_FOREIGN_CORPORATIONS_MANUFACTURED_PAYMENT = (
        "DIVIDENDS_PAID_BY_FOREIGN_CORPORATIONS_MANUFACTURED_PAYMENT"
    )
    CAPITAL_GAINS_MANUFACTURED_PAYMENT = "CAPITAL_GAINS_MANUFACTURED_PAYMENT"
    REAL_PROPERTY_INCOME_AND_NATURAL_RESOURCES_ROYALTIES_MANUFACTURED_PAYMENT = (
        "REAL_PROPERTY_INCOME_AND_NATURAL_RESOURCES_ROYALTIES_MANUFACTURED_PAYMENT"
    )
    OTHER_INCOME_MANUFACTURED_PAYMENT = "OTHER_INCOME_MANUFACTURED_PAYMENT"
    QUALIFIED_INVESTMENT_ENTITY_MANUFACTURED_PAYMENT = (
        "QUALIFIED_INVESTMENT_ENTITY_MANUFACTURED_PAYMENT"
    )
    TRUST_DISTRIBUTION_MANUFACTURED_PAYMENT = "TRUST_DISTRIBUTION_MANUFACTURED_PAYMENT"
    PUBLICLY_TRADED_PARTNERSHIP_DISTRIBUTION_MANUFACTURED_PAYMENT = (
        "PUBLICLY_TRADED_PARTNERSHIP_DISTRIBUTION_MANUFACTURED_PAYMENT"
    )
    CAPITAL_GAINS_DISTRIBUTION_MANUFACTURED_PAYMENT = (
        "CAPITAL_GAINS_DISTRIBUTION_MANUFACTURED_PAYMENT"
    )
    RETURN_OF_CAPITAL_MANUFACTURED_PAYMENT = "RETURN_OF_CAPITAL_MANUFACTURED_PAYMENT"
    OTHER_DIVIDEND_EQUIVALENT_MANUFACTURED_PAYMENT = (
        "OTHER_DIVIDEND_EQUIVALENT_MANUFACTURED_PAYMENT"
    )
    TAX_EVENT_1446F_FOR_PUBLICLY_TRADED_SECURITIES_MANUFACTURED_PAYMENT = (
        "TAX_EVENT_1446F_FOR_PUBLICLY_TRADED_SECURITIES_MANUFACTURED_PAYMENT"
    )
    PTP_UNCHARACTERISED_INCOME_MANUFACTURED_PAYMENT = (
        "PTP_UNCHARACTERISED_INCOME_MANUFACTURED_PAYMENT"
    )
    MULTIPLE_1042S_TAX_COMPONENTS_MANUFACTURED_PAYMENT = (
        "MULTIPLE_1042S_TAX_COMPONENTS_MANUFACTURED_PAYMENT"
    )
    DIVIDEND_MANUFACTURED_PAYMENT = "DIVIDEND_MANUFACTURED_PAYMENT"
    SHORT_TERM_CAPITAL_GAINS_MANUFACTURED_PAYMENT = (
        "SHORT_TERM_CAPITAL_GAINS_MANUFACTURED_PAYMENT"
    )
    LONG_TERM_CAPITAL_GAINS_MANUFACTURED_PAYMENT = (
        "LONG_TERM_CAPITAL_GAINS_MANUFACTURED_PAYMENT"
    )
    PROPERTY_INCOME_DISTRIBUTION_MANUFACTURED_PAYMENT = (
        "PROPERTY_INCOME_DISTRIBUTION_MANUFACTURED_PAYMENT"
    )
    TAX_EXEMPTED_MANUFACTURED_PAYMENT = "TAX_EXEMPTED_MANUFACTURED_PAYMENT"


class TransactionType(StrEnum):
    WITHDRAW = "WITHDRAW"
    DEPOSIT = "DEPOSIT"
    FEE = "FEE"
    TRANSFER = "TRANSFER"


class ReportStatus(StrEnum):
    QUEUED = "Queued"
    PROCESSING = "Processing"
    RUNNING = "Running"
    CANCELED = "Canceled"
    FAILED = "Failed"
    FINISHED = "Finished"


class InstrumentIssueName(StrEnum):
    DELISTED = "DELISTED"
    SUSPENDED = "SUSPENDED"
    NO_LONGER_TRADABLE = "NO_LONGER_TRADABLE"
    MAX_POSITION_SIZE_REACHED = "MAX_POSITION_SIZE_REACHED"
    APPROACHING_MAX_POSITION_SIZE = "APPROACHING_MAX_POSITION_SIZE"
    COMPLEX_INSTRUMENT_APP_TEST_REQUIRED = "COMPLEX_INSTRUMENT_APP_TEST_REQUIRED"
    PRICE_TOO_LOW = "PRICE_TOO_LOW"


class IssueSeverity(StrEnum):
    IRREVERSIBLE = "IRREVERSIBLE"
    REVERSIBLE = "REVERSIBLE"
    INFORMATIVE = "INFORMATIVE"
